import ../../routes/registration.http
import ../../routes/authentication.http
import ../../routes/project.http



run #ConnectSignup(@connectId=user-1-connect-id, @email=user-1@test.com, @name=User One)
###
run #ConnectSignup(@connectId=user-2-connect-id, @email=user-2@test.com, @name=User Two)
###
run #Token(@connectId=user-1-connect-id)
###
run #CreateProject(@projectTitle=Test Project2)
###
run #AddUser(@connectId=user-2-connect-id, @role=Proofer)
###
